-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."data_consumption" add column "number_of_events" integer
--  not null default '1';
