-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "service_provider"."service_link" add column "customer_flyer_links" jsonb
--  null;
