-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "service_provider"."influencer_payouts" add column "sp_type" text
--  not null;
