-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "service_provider"."offer_applied" add column "service_provider_id" integer
--  null;
