-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "taxi"."order" add column "order_time" timestamp with time zone
--  not null default now();
